// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBH8HiSqzXlcVMrz-CokxJeyf2utu2RuM',
    appId: '1:185360620575:web:21dd917a6cbeeb3e2e092a',
    messagingSenderId: '185360620575',
    projectId: 'stream24-news',
    authDomain: 'stream24-news.firebaseapp.com',
    storageBucket: 'stream24-news.firebasestorage.app',
    measurementId: 'G-76NG92RWRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1DxP3QOyZD-4psm4bfUtknYEksbhb9A',
    appId: '1:185360620575:android:7ddbf4b2b8a05ae72e092a',
    messagingSenderId: '185360620575',
    projectId: 'stream24-news',
    storageBucket: 'stream24-news.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6kCFxHCKi1Zwl-40IAHZCtRHLUIaVhdk',
    appId: '1:185360620575:ios:241909d0864e0df62e092a',
    messagingSenderId: '185360620575',
    projectId: 'stream24-news',
    storageBucket: 'stream24-news.firebasestorage.app',
    iosBundleId: 'com.legendarysoftware.stream24news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6kCFxHCKi1Zwl-40IAHZCtRHLUIaVhdk',
    appId: '1:185360620575:ios:241909d0864e0df62e092a',
    messagingSenderId: '185360620575',
    projectId: 'stream24-news',
    storageBucket: 'stream24-news.firebasestorage.app',
    iosBundleId: 'com.legendarysoftware.stream24news',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBH8HiSqzXlcVMrz-CokxJeyf2utu2RuM',
    appId: '1:185360620575:web:2fba98fc562478632e092a',
    messagingSenderId: '185360620575',
    projectId: 'stream24-news',
    authDomain: 'stream24-news.firebaseapp.com',
    storageBucket: 'stream24-news.firebasestorage.app',
    measurementId: 'G-NEW2BR2PTV',
  );
}
